=== SerbiaStrong-220/space-station-14/Schemas/rsi.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "JSON Schema for SS14 RSI validation.",
    "examples": [
        {
            "version": 1,
            "license": "CC-BY-SA-3.0",
            "copyright": "Taken from CODEBASE at COMMIT PERMALINK",
            "size": {
                "x": 32,
                "y": 32
            },
            "states": [
                {
                    "name": "basic"
                },
                {
                    "name": "basic-directions",
                    "directions": 4
                },
                {
                    "name": "basic-delays",
                    "delays": [
                        [
                            0.1,
                            0.1
                        ]
                    ]
                },
                {
                    "name": "basic-delays-directions",
                    "directions": 4,
                    "delays": [
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ]
                    ]
                }
            ]
        }
    ],
    "required": [
        "version",
        "license",
        "copyright",
        "size",
        "states"
    ],
    "title": "RSI Schema",
    "type": "object",
    "properties": {
        "version": {
            "$id": "#/properties/version",
            "default": "",
            "description": "RSI version integer.",
            "title": "The version schema",
            "type": "integer"
        },
        "license": {
            "$id": "#/properties/license",
            "default": "",
            "description": "The license for the associated icon states. Restricted to SS14-compatible asset licenses.",
            "enum": [
                "CC-BY-3.0",
                "CC-BY-4.0",
                "CC-BY-SA-3.0",
                "CC-BY-SA-4.0",
                "CC-BY-NC-3.0",
                "CC-BY-NC-4.0",
                "CC-BY-NC-SA-3.0",
                "CC-BY-NC-SA-4.0",
                "CC0-1.0",
				"OFL",
				"EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
                "Custom"
            ],
            "examples": [
                "CC-BY-SA-3.0"
            ],
            "title": "License",
            "type": "string"
        },
        "copyright": {
            "$id": "#/properties/copyright",
            "title": "Copyright Info",
            "description": "The copyright holder. This is typically a link to the commit of the codebase that the icon is pulled from.",
            "default": "",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "examples": [
                "Taken from CODEBASE at COMMIT LINK",
                [
                    "(License-1) First Author",
                    "(License-2) Second Author"
                ]
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "default": {},
            "description": "The dimensions of the sprites inside the RSI.  This is not the size of the PNG files that store the sprite sheet.",
            "examples": [
                {
                    "x": 32,
                    "y": 32
                }
            ],
            "title": "Sprite Dimensions",
            "required": [
                "x",
                "y"
            ],
            "type": "object",
            "properties": {
                "x": {
                    "$id": "#/properties/size/properties/x",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                },
                "y": {
                    "$id": "#/properties/size/properties/y",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                }
            },
            "additionalProperties": true
        },
        "states": {
            "$id": "#/properties/states",
            "type": "array",
            "title": "Icon States",
            "description": "Metadata for icon states. Includes name, directions, delays, etc.",
            "default": [],
            "examples": [
                [
                    {
                        "name": "basic"
                    },
                    {
                        "name": "basic-directions",
                        "directions": 4
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/states/items",
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "directions": {
                        "type": "integer",
                        "enum": [
                            1,
                            4,
                            8
                        ]
                    },
                    "delays": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/MetaFlud/Clothing/OuterClothing/apron.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "MetaFlud",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-OUTERCLOTHING",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Weapons/Guns/Revolvers/legendary_marksman.rsi/meta.json
{
    "version": 1,
    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
    "copyright": "Sprited by matriotic (Discord) for SS220",
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "icon"
        },
        {
            "name": "bolt-open"
        },
        {
            "name": "inhand-left",
            "directions": 4
        },
        {
            "name": "inhand-right",
            "directions": 4
        },
        {
            "name": "equipped-BELT",
            "directions": 4
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Structures/Machines/cluwneComms.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "MadSkaven",
  "size": {
    "x": 32,
    "y": 32
  },
    "states": [
        {
            "name": "computer",
            "directions": 4
        },
        {
            "name": "generic_keyboard",
            "directions": 4
        },
        {
            "name": "generic_keys",
            "directions": 4,
            "delays": [
                [
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2
                ]
            ]
        },
        {
            "name": "generic",
            "directions": 4,
            "delays": [
                [
                    0.2,
                    0.2,
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2,
                    0.2,
                    0.2
                ],
                [
                    0.2,
                    0.2,
                    0.2,
                    0.2,
                    0.2
                ]
            ]
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/OuterClothing/Armor/blueshield_bulletproof.rsi/meta.json
{
    "version": 1,
    "license": "CC-BY-SA-3.0",
    "copyright": "Taken/modified by Taral from tgstation at commit https://github.com/tgstation/tgstation/commit/dbc2435fa562f4ef130a7112d2a4cc9c80099894. Vox states by Flareguy for Space Station 14. Resprited by Estkemran (Github) for SS220. Resomi states sprited by abubben (Discord) for ss220",
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "icon"
        },
        {
            "name": "equipped-OUTERCLOTHING",
            "directions": 4
        },
        {
            "name": "equipped-OUTERCLOTHING-resomi",
            "directions": 4
        },
        {
            "name": "equipped-OUTERCLOTHING-vox",
            "directions": 4
        },
        {
            "name": "inhand-left",
            "directions": 4
        },
        {
            "name": "inhand-right",
            "directions": 4
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Devices/eftpos.rsi/meta.json
{
    "version": 1,
    "size": {
        "x": 32,
        "y": 32
    },
    "license": "CC-BY-SA-3.0",
    "copyright": "Taken from ParadiseSS13 at commit https://github.com/ParadiseSS13/Paradise/commit/0c6802fdb26fe49477447daae2b343e59ee90e5a",
    "states": [
        {
            "name": "eftpos"
        },
        {
            "name": "eftpos-screen"
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Interface/Actions/MinorFauna/action_tarantula.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Sprited by Estkemran (Github) modified by kimorue (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "tarantula_spawn"
    },
    {
      "name": "web_spawn"
    },
    {
      "name": "wall_spawn"
    },
    {
      "name": "prying"
    },
    {
      "name": "cocoon"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Structures/Specific/bags.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Made by gabova (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "bagpile1"
    },
    {
      "name": "bagpile2"
    },
    {
      "name": "bagpile3"
    },
    {
      "name": "bagpile4"
    },
    {
      "name": "bagpile5"
    },
    {
      "name": "bagpile6"
    },
    {
      "name": "bagpile7"
    },
    {
      "name": "bagpile8"
    },
    {
      "name": "bagpile9"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/Structures/Windows/reinforced_window.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Made by MIXnikita for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "full"
    },
    {
      "name": "rwindow0",
      "directions": 4
    },
    {
      "name": "rwindow1",
      "directions": 4
    },
    {
      "name": "rwindow2",
      "directions": 4
    },
    {
      "name": "rwindow3",
      "directions": 4
    },
    {
      "name": "rwindow4",
      "directions": 4
    },
    {
      "name": "rwindow5",
      "directions": 4
    },
    {
      "name": "rwindow6",
      "directions": 4
    },
    {
      "name": "rwindow7",
      "directions": 4
    }
  ]
}
