=== SerbiaStrong-220/space-station-14/Schemas/rsi.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "JSON Schema for SS14 RSI validation.",
    "examples": [
        {
            "version": 1,
            "license": "CC-BY-SA-3.0",
            "copyright": "Taken from CODEBASE at COMMIT PERMALINK",
            "size": {
                "x": 32,
                "y": 32
            },
            "states": [
                {
                    "name": "basic"
                },
                {
                    "name": "basic-directions",
                    "directions": 4
                },
                {
                    "name": "basic-delays",
                    "delays": [
                        [
                            0.1,
                            0.1
                        ]
                    ]
                },
                {
                    "name": "basic-delays-directions",
                    "directions": 4,
                    "delays": [
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ]
                    ]
                }
            ]
        }
    ],
    "required": [
        "version",
        "license",
        "copyright",
        "size",
        "states"
    ],
    "title": "RSI Schema",
    "type": "object",
    "properties": {
        "version": {
            "$id": "#/properties/version",
            "default": "",
            "description": "RSI version integer.",
            "title": "The version schema",
            "type": "integer"
        },
        "license": {
            "$id": "#/properties/license",
            "default": "",
            "description": "The license for the associated icon states. Restricted to SS14-compatible asset licenses.",
            "enum": [
                "CC-BY-3.0",
                "CC-BY-4.0",
                "CC-BY-SA-3.0",
                "CC-BY-SA-4.0",
                "CC-BY-NC-3.0",
                "CC-BY-NC-4.0",
                "CC-BY-NC-SA-3.0",
                "CC-BY-NC-SA-4.0",
                "CC0-1.0",
				"OFL",
				"EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
                "Custom"
            ],
            "examples": [
                "CC-BY-SA-3.0"
            ],
            "title": "License",
            "type": "string"
        },
        "copyright": {
            "$id": "#/properties/copyright",
            "title": "Copyright Info",
            "description": "The copyright holder. This is typically a link to the commit of the codebase that the icon is pulled from.",
            "default": "",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "examples": [
                "Taken from CODEBASE at COMMIT LINK",
                [
                    "(License-1) First Author",
                    "(License-2) Second Author"
                ]
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "default": {},
            "description": "The dimensions of the sprites inside the RSI.  This is not the size of the PNG files that store the sprite sheet.",
            "examples": [
                {
                    "x": 32,
                    "y": 32
                }
            ],
            "title": "Sprite Dimensions",
            "required": [
                "x",
                "y"
            ],
            "type": "object",
            "properties": {
                "x": {
                    "$id": "#/properties/size/properties/x",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                },
                "y": {
                    "$id": "#/properties/size/properties/y",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                }
            },
            "additionalProperties": true
        },
        "states": {
            "$id": "#/properties/states",
            "type": "array",
            "title": "Icon States",
            "description": "Metadata for icon states. Includes name, directions, delays, etc.",
            "default": [],
            "examples": [
                [
                    {
                        "name": "basic"
                    },
                    {
                        "name": "basic-directions",
                        "directions": 4
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/states/items",
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "directions": {
                        "type": "integer",
                        "enum": [
                            1,
                            4,
                            8
                        ]
                    },
                    "delays": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Effects/cult_yogg_cleansing.rsi/meta.json
{
    "version": 1,
    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
    "copyright": "Made by Mixnikita for SS220",
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "cleansingEffect",
            "delays": [
                [
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15
                ]
            ]
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Neck/Cloaks/centcomm_fo.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/5a73e8f825ff279e82949b9329783a9e3070e2da, sprites in hand by PuroSlavKing (Github) and RudeyCoolLeet#3875, colors edited by noctyrnal (github) modified by MrALPAKA for SS220, colors edited by EstKemran (Github) for SS220, resomi states sprited by abubben (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-NECK",
      "directions": 4
    },
	  {
      "name": "equipped-NECK-resomi",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Head/Helmets/spaceninja.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from TG Station https://github.com/tgstation/tgstation/blob/HEAD/icons/mob/clothing/modsuit/mod_clothing.dmi, vox state taken from Skyrat TG Station https://github.com/Skyrat-SS13/Skyrat-tg/blob/HEAD/modular_skyrat/modules/better_vox/icons/clothing/mod.dmi",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "icon-flash"
    },
    {
      "name": "off-equipped-HELMET",
      "directions": 4
    },
    {
      "name": "off-equipped-HELMET-vox",
      "directions": 4
    },
    {
      "name": "on-equipped-HELMET",
      "directions": 4
    },
    {
      "name": "on-equipped-HELMET-vox",
      "directions": 4
    },
    {
      "name": "off-inhand-left",
      "directions": 4
    },
    {
      "name": "off-inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Misc/business_card.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "By Aserovich, modified by Estkemran (Github) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "iaa_card"
    },
    {
      "name": "law_card"
    },
    {
      "name": "magistrate_card"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell_big.rsi/meta.json
{
    "version": 1,
    "size": {
        "x": 32,
        "y": 32
    },
    "license": "CC-BY-SA-3.0",
    "copyright": "Taken from CEV-Eris at commit 5d8b4cf30ac37f0b8e7d78c349344086b95ab4ae, modified by lexaSvarshik (github)",
    "states": [
        {
            "name": "incendiary"
        },
        {
            "name": "incendiary-spent"
        },
        {
            "name": "lethal"
        },
        {
            "name": "lethal-spent"
        },
        {
            "name": "practice"
        },
        {
            "name": "practice-spent"
        },
        {
            "name": "rubber"
        },
        {
            "name": "rubber-spent"
        },
        {
            "name": "rubber_slug"
        },
        {
            "name": "rubber_slug-spent"
        },
        {
            "name": "slug"
        },
        {
            "name": "slug-spent"
        },
        {
            "name": "steel_slug"
        },
        {
            "name": "steel_slug-spent"
        },
        {
            "name": "flechette"
        },
        {
            "name": "flechette-spent"
        },
        {
            "name": "blank"
        },
        {
            "name": "blank-spent"
        },
        {
            "name": "flare"
        },
        {
            "name": "flare-spent"
        },
        {
            "name": "highvelocity"
        },
        {
            "name": "highvelocity-spent"
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/OuterClothing/Armor/mech_loader.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Made by mixnikita (Discord) for SS220, resomi states sprited by abubben (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-OUTERCLOTHING",
      "directions": 4
    },
    {
      "name": "equipped-OUTERCLOTHING-resomi",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Interface/Actions/ninja.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Made by .kreks. (Discord) and Estkemran (Github)",
  "size":
  {
    "x": 32,
    "y": 32
  },
  "states":
  [
    {
      "name": "ninjadash"
    },
    {
      "name": "ninjaEMP"
    },
    {
        "name": "ninjaGlovesOff"
    },
    {
        "name": "ninjaGlovesOn"
    },
    {
        "name": "ninjaInvisible"
    },
    {
        "name": "ninjaTeleport"
    },
    {
        "name": "ninjaThrowingStar"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Mechs/altcores.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Made by PorteRianes, https://github.com/PorteRianes",
  "size": {
    "x": 64,
    "y": 64
  },
  "states": [
    {
        "name": "basicloader",
        "directions": 4
    },
    {
        "name": "basicloadercolor",
        "directions": 4
    }
  ]
}
