=== SerbiaStrong-220/space-station-14/Schemas/rsi.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "JSON Schema for SS14 RSI validation.",
    "examples": [
        {
            "version": 1,
            "license": "CC-BY-SA-3.0",
            "copyright": "Taken from CODEBASE at COMMIT PERMALINK",
            "size": {
                "x": 32,
                "y": 32
            },
            "states": [
                {
                    "name": "basic"
                },
                {
                    "name": "basic-directions",
                    "directions": 4
                },
                {
                    "name": "basic-delays",
                    "delays": [
                        [
                            0.1,
                            0.1
                        ]
                    ]
                },
                {
                    "name": "basic-delays-directions",
                    "directions": 4,
                    "delays": [
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ]
                    ]
                }
            ]
        }
    ],
    "required": [
        "version",
        "license",
        "copyright",
        "size",
        "states"
    ],
    "title": "RSI Schema",
    "type": "object",
    "properties": {
        "version": {
            "$id": "#/properties/version",
            "default": "",
            "description": "RSI version integer.",
            "title": "The version schema",
            "type": "integer"
        },
        "license": {
            "$id": "#/properties/license",
            "default": "",
            "description": "The license for the associated icon states. Restricted to SS14-compatible asset licenses.",
            "enum": [
                "CC-BY-3.0",
                "CC-BY-4.0",
                "CC-BY-SA-3.0",
                "CC-BY-SA-4.0",
                "CC-BY-NC-3.0",
                "CC-BY-NC-4.0",
                "CC-BY-NC-SA-3.0",
                "CC-BY-NC-SA-4.0",
                "CC0-1.0",
				"OFL",
				"EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
                "Custom"
            ],
            "examples": [
                "CC-BY-SA-3.0"
            ],
            "title": "License",
            "type": "string"
        },
        "copyright": {
            "$id": "#/properties/copyright",
            "title": "Copyright Info",
            "description": "The copyright holder. This is typically a link to the commit of the codebase that the icon is pulled from.",
            "default": "",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "examples": [
                "Taken from CODEBASE at COMMIT LINK",
                [
                    "(License-1) First Author",
                    "(License-2) Second Author"
                ]
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "default": {},
            "description": "The dimensions of the sprites inside the RSI.  This is not the size of the PNG files that store the sprite sheet.",
            "examples": [
                {
                    "x": 32,
                    "y": 32
                }
            ],
            "title": "Sprite Dimensions",
            "required": [
                "x",
                "y"
            ],
            "type": "object",
            "properties": {
                "x": {
                    "$id": "#/properties/size/properties/x",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                },
                "y": {
                    "$id": "#/properties/size/properties/y",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                }
            },
            "additionalProperties": true
        },
        "states": {
            "$id": "#/properties/states",
            "type": "array",
            "title": "Icon States",
            "description": "Metadata for icon states. Includes name, directions, delays, etc.",
            "default": [],
            "examples": [
                [
                    {
                        "name": "basic"
                    },
                    {
                        "name": "basic-directions",
                        "directions": 4
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/states/items",
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "directions": {
                        "type": "integer",
                        "enum": [
                            1,
                            4,
                            8
                        ]
                    },
                    "delays": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Structures/Machines/grill_advanced.rsi/meta.json
{
  "version": 1,
  "license": "CC0-1.0",
  "copyright": "Original base by deltanedas (github) for SS14. Resprited by (DISCORD)@ps3moira#9488. Resprited by KREKS. Resprited by TonyBigShoes (Github) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "low"
    },
    {
      "name": "medium"
    },
    {
      "name": "high"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/Structures/Storage/Crates/engineering.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from tgstation at commit 9b3b026a7590372e42ecb9c44283c1ea17bba506, modified by TheArturZh for SS220, custom welded sprite from SS14 by comasqw",
  "size": {
    "x": 32,
    "y": 48
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "closed"
    },
    {
      "name": "open"
    },
    {
      "name": "welded"
    },
    {
      "name": "sparking",
      "delays": [
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ]
      ]
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Head/Hats/ntr_tophat.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-4.0",
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e, resprited by dinazewwr (discord)",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-HELMET",
      "directions": 4
    },
    {
      "name": "equipped-HELMET-hamster",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/OuterClothing/Armor/streetjudge.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from tgstation at commit https://github.com/ss220-space/Paradise/blob/HEAD/icons/mob/clothing/suits.dmi",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-OUTERCLOTHING",
      "directions": 4
    },
    {
      "name": "equipped-OUTERCLOTHING-vox",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Weapons/Melee/Misc/expensivestick.rsi/meta.json
{
    "version": 1,
    "license": "CC-BY-SA-3.0",
    "copyright": "Sprited by dimwerdp (discord) for SS220",
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "icon"
        },
        {
            "name": "inhand-left",
            "directions": 4
        },
        {
            "name": "inhand-right",
            "directions": 4
        },
        {
            "name": "wielded-inhand-left",
            "directions": 4
        },
        {
            "name": "wielded-inhand-right",
            "directions": 4
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Decals/trimline_warn.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "taken from tgstation at https://github.com/tgstation/tgstation/blob/0a75b1793757ead97549ee238d4332caa0769e28/icons/turf/decals.dmi",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "trimline_corner_warn_ne"
    },
    {
      "name": "trimline_corner_warn_nw"
    },
    {
      "name": "trimline_corner_warn_se"
    },
    {
      "name": "trimline_corner_warn_sw"
    },
    {
      "name": "trimline_line_warn_e"
    },
    {
      "name": "trimline_line_warn_n"
    },
    {
      "name": "trimline_line_warn_s"
    },
    {
      "name": "trimline_line_warn_w"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Neck/Cloaks/Blueshield.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "based on SS13 https://github.com/ss220-space/Paradise/blob/f04540b212de5bf1919f7f1a52a7e20f0892a00e/icons/mob/clothing/neck.dmi , modify on ss14 by 363679417022676992 (Discord)",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
	{
      "name": "equipped-NECK",
      "directions": 4
    },
	{
      "name": "inhand-left",
      "directions": 4
    },
	{
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Mobs/Ghosts/ghost_human.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "https://github.com/tgstation/tgstation/blob/f80e7ba62d27c77cfeac709dd71033744d0015c4/icons/mob/mob.dmi, cap sprited by plagexx (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "animated",
      "directions": 4
    },
    {
      "name": "cap",
      "directions": 4
    },
    {
      "name": "icon"
    }
  ]
}
